import os
from contextlib import contextmanager

import psycopg2
from psycopg2.extensions import TRANSACTION_STATUS_INERROR
from psycopg2.extras import RealDictCursor
from psycopg2.pool import SimpleConnectionPool

_pool: SimpleConnectionPool | None = None


def _allow_explicit_ids(conn) -> None:
    """App inserts use MAX(id)+1. GENERATED ALWAYS rejects those values."""
    with conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute(
            """
            SELECT table_name, column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND is_identity = 'YES'
              AND identity_generation = 'ALWAYS'
            """
        )
        rows = cur.fetchall()
        for row in rows:
            cur.execute(
                f'ALTER TABLE "{row["table_name"]}" ALTER COLUMN "{row["column_name"]}" SET GENERATED BY DEFAULT'
            )
    conn.commit()


def init_pool() -> None:
    global _pool
    if _pool is not None:
        return
    _pool = SimpleConnectionPool(
        minconn=1,
        maxconn=16,
        host=os.getenv("SUPABASE_DB_HOST"),
        port=os.getenv("SUPABASE_DB_PORT", "5432"),
        dbname=os.getenv("SUPABASE_DB_NAME", "postgres"),
        user=os.getenv("SUPABASE_DB_USER"),
        password=os.getenv("SUPABASE_DB_PASSWORD"),
        sslmode=os.getenv("SUPABASE_DB_SSLMODE", "require"),
    )
    conn = _pool.getconn()
    try:
        _allow_explicit_ids(conn)
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS password_reset_tokens (
                    token_hash VARCHAR(64) PRIMARY KEY,
                    customer_id INTEGER,
                    user_id INTEGER,
                    expires_at TIMESTAMPTZ NOT NULL,
                    used_at TIMESTAMPTZ
                )
                """
            )
            cur.execute("ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS user_id INTEGER")
            cur.execute("ALTER TABLE password_reset_tokens ALTER COLUMN customer_id DROP NOT NULL")
            cur.execute(
                "CREATE INDEX IF NOT EXISTS idx_password_reset_customer ON password_reset_tokens (customer_id)"
            )
            cur.execute(
                "CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens (user_id)"
            )
        conn.commit()
        try:
            from app.profile_photos import ensure_profile_photo_columns
            ensure_profile_photo_columns(conn)
        except Exception:
            conn.rollback()
        try:
            from app.automation import ensure_automation_schema
            ensure_automation_schema(conn)
        except Exception:
            conn.rollback()
    finally:
        _pool.putconn(conn)


@contextmanager
def get_conn():
    if _pool is None:
        init_pool()
    conn = _pool.getconn()
    try:
        yield conn
        if conn.get_transaction_status() == TRANSACTION_STATUS_INERROR:
            conn.rollback()
        else:
            conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        _pool.putconn(conn)


def fetch_one(sql: str, params=None):
    with get_conn() as conn:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(sql, params or ())
            return cur.fetchone()


def fetch_all(sql: str, params=None):
    with get_conn() as conn:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(sql, params or ())
            return cur.fetchall()


def next_id(cur, table: str, column: str) -> int:
    cur.execute(f"SELECT COALESCE(MAX({column}), 0) + 1 AS nid FROM {table}")
    row = cur.fetchone()
    if isinstance(row, dict):
        return int(row["nid"])
    return int(row[0])
