import os
import threading
from contextlib import contextmanager

import psycopg2
from psycopg2.extensions import TRANSACTION_STATUS_INERROR
from psycopg2.extras import RealDictCursor
from psycopg2.pool import SimpleConnectionPool

_pool: SimpleConnectionPool | None = None
_pool_lock = threading.Lock()


def _allow_explicit_ids(conn) -> None:
    """App inserts use MAX(id)+1. GENERATED ALWAYS rejects those values."""
    with conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute(
            """
            SELECT table_name, column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND is_identity = 'YES'
              AND identity_generation = 'ALWAYS'
            """
        )
        rows = cur.fetchall()
        for row in rows:
            cur.execute(
                f'ALTER TABLE "{row["table_name"]}" ALTER COLUMN "{row["column_name"]}" SET GENERATED BY DEFAULT'
            )
    conn.commit()


def _fix_sales_customer_fk(conn) -> None:
    """POS sales must point at customers, not users. customer_id 0 is a valid customer."""
    with conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute(
            """
            SELECT ccu.table_name AS foreign_table
            FROM information_schema.table_constraints tc
            JOIN information_schema.constraint_column_usage ccu
              ON ccu.constraint_name = tc.constraint_name
             AND ccu.table_schema = tc.table_schema
            WHERE tc.table_schema = 'public'
              AND tc.table_name = 'sales'
              AND tc.constraint_type = 'FOREIGN KEY'
              AND tc.constraint_name = 'sales_ibfk_2'
            """
        )
        row = cur.fetchone()
        if row and str(row.get("foreign_table") or "").lower() == "users":
            cur.execute("ALTER TABLE sales DROP CONSTRAINT sales_ibfk_2")
        cur.execute(
            """
            UPDATE sales s
            SET customer_id = NULL
            WHERE s.customer_id IS NOT NULL
              AND NOT EXISTS (
                  SELECT 1 FROM customers c WHERE c.customer_id = s.customer_id
              )
            """
        )
        cur.execute(
            """
            SELECT 1
            FROM information_schema.table_constraints
            WHERE table_schema = 'public'
              AND table_name = 'sales'
              AND constraint_name = 'sales_customer_id_fkey'
            """
        )
        if cur.fetchone() is None:
            cur.execute(
                """
                ALTER TABLE sales
                ADD CONSTRAINT sales_customer_id_fkey
                FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
                """
            )
    conn.commit()


def init_pool() -> None:
    global _pool
    with _pool_lock:
        if _pool is not None:
            return
        _open_pool()


def _open_pool() -> None:
    global _pool
    last_error = None
    for _attempt in range(1):
        try:
            _pool = SimpleConnectionPool(
                minconn=1,
                maxconn=4,
                host=os.getenv("SUPABASE_DB_HOST"),
                port=os.getenv("SUPABASE_DB_PORT", "5432"),
                dbname=os.getenv("SUPABASE_DB_NAME", "postgres"),
                user=os.getenv("SUPABASE_DB_USER"),
                password=os.getenv("SUPABASE_DB_PASSWORD"),
                sslmode=os.getenv("SUPABASE_DB_SSLMODE", "require"),
                connect_timeout=8,
                gssencmode="disable",
                keepalives=1,
                keepalives_idle=30,
                keepalives_interval=10,
                keepalives_count=3,
            )
            break
        except Exception as exc:
            last_error = exc
            _pool = None
            import time
            time.sleep(3)
    if _pool is None:
        raise last_error
    conn = _pool.getconn()
    try:
        _allow_explicit_ids(conn)
        try:
            _fix_sales_customer_fk(conn)
        except Exception:
            conn.rollback()
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS password_reset_tokens (
                    token_hash VARCHAR(64) PRIMARY KEY,
                    customer_id INTEGER,
                    user_id INTEGER,
                    expires_at TIMESTAMPTZ NOT NULL,
                    used_at TIMESTAMPTZ
                )
                """
            )
            cur.execute("ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS user_id INTEGER")
            cur.execute("ALTER TABLE password_reset_tokens ALTER COLUMN customer_id DROP NOT NULL")
            cur.execute(
                "CREATE INDEX IF NOT EXISTS idx_password_reset_customer ON password_reset_tokens (customer_id)"
            )
            cur.execute(
                "CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens (user_id)"
            )
        conn.commit()
        try:
            from app.profile_photos import ensure_profile_photo_columns
            ensure_profile_photo_columns(conn)
        except Exception:
            conn.rollback()
        try:
            from app.automation import ensure_automation_schema
            ensure_automation_schema(conn)
        except Exception:
            conn.rollback()
        try:
            from app.loyalty import ensure_loyalty_settings
            ensure_loyalty_settings(conn)
        except Exception:
            conn.rollback()
    finally:
        _pool.putconn(conn)


def _discard(conn) -> None:
    try:
        _pool.putconn(conn, close=True)
    except Exception:
        try:
            conn.close()
        except Exception:
            pass


@contextmanager
def get_conn():
    if _pool is None:
        init_pool()
    conn = _pool.getconn()
    try:
        if conn.closed:
            raise psycopg2.OperationalError("connection already closed")
        yield conn
        if conn.closed:
            return
        if conn.get_transaction_status() == TRANSACTION_STATUS_INERROR:
            conn.rollback()
        else:
            conn.commit()
    except Exception:
        try:
            if not conn.closed:
                conn.rollback()
        except Exception:
            pass
        _discard(conn)
        conn = None
        raise
    else:
        _pool.putconn(conn)


def fetch_one(sql: str, params=None):
    with get_conn() as conn:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(sql, params or ())
            return cur.fetchone()


def fetch_all(sql: str, params=None):
    with get_conn() as conn:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(sql, params or ())
            return cur.fetchall()


def next_id(cur, table: str, column: str) -> int:
    cur.execute(f"SELECT COALESCE(MAX({column}), 0) + 1 AS nid FROM {table}")
    row = cur.fetchone()
    if isinstance(row, dict):
        return int(row["nid"])
    return int(row[0])
